version: '3'

services:
  mysql:
    image: mysql:5.7
    env_file:
      - mysql.env
  ftp-server:
    image: atmoz/sftp
    ports:
        - 22:22
    env_file:
      - sftp.env
  airflow:
    image: docker-whirl-airflow:py-${PYTHON_VERSION}-local
    ports:
      - '5000:5000'  # HTTP (Airflow Web UI)
    env_file:
      - mysql.env
      - sftp.env
      - .whirl.env
    environment:
      - WHIRL_SETUP_FOLDER
      - UNPAUSE_DAG
    volumes:
      - $DAG_FOLDER:/usr/local/airflow/dags/$PROJECTNAME
      - ${ENVIRONMENT_FOLDER}/whirl.setup.d:${WHIRL_SETUP_FOLDER}/env.d/
      - ${DAG_FOLDER}/whirl.setup.d:${WHIRL_SETUP_FOLDER}/dag.d/
      - ${MOCK_DATA_FOLDER}:/mock-data
    depends_on:
      - ftp-server
      - mysql
